export const TIME_DEFAULTS = {
  HOURS_TO_MINUTES: 60,
  COARSE_STEP_MINUTES: 5,
  FINE_STEP_MINUTES: 2,
  PADDING_MINUTES: 20,
  FINE_TUNING_THRESHOLD_HOURS: 12,
  MS_IN_MINUTE: 60_000,
  MS_IN_HOUR: 3_600_000,
  MINUTES_PER_WEEK: 10080,
} as const;
